
const dict = {
  en: {
    age_title: "Age Confirmation",
    age_text: "You must be 18+ to play. Confirm to continue.",
    age_btn: "I am 18+",
    login_title: "Sign In",
    email: "Email",
    password: "Password",
    login_btn: "Sign In",
    forgot: "Forgot password?",
    no_account: "No account?",
    to_register: "Create account",
    register_title: "Create Account",
    rating: "Start Rating",
    avatar: "Avatar",
    register_btn: "Register",
    to_login: "Back to sign in",
    lobby_title: "Lobby",
    difficulty: "Difficulty",
    mode: "Mode",
    duel: "Duel (2 players)",
    solo: "Solo",
    create_table: "Create table",
    active_tables: "Active tables",
    online_players: "Players online",
    rating_filter: "Min rating",
    score: "Score",
    tokens: "Tokens",
    turn: "Turn",
    leave: "Leave"
  },
  ru: {
    age_title: "Подтверждение возраста",
    age_text: "Для игры нужно 18+. Подтвердите продолжение.",
    age_btn: "Мне 18+",
    login_title: "Вход",
    email: "Email",
    password: "Пароль",
    login_btn: "Войти",
    forgot: "Забыли пароль?",
    no_account: "Нет аккаунта?",
    to_register: "Создать аккаунт",
    register_title: "Регистрация",
    rating: "Стартовый рейтинг",
    avatar: "Аватар",
    register_btn: "Зарегистрироваться",
    to_login: "Назад ко входу",
    lobby_title: "Лобби",
    difficulty: "Сложность",
    mode: "Режим",
    duel: "Дуэль (2 игрока)",
    solo: "Одиночная",
    create_table: "Создать стол",
    active_tables: "Активные столы",
    online_players: "Игроки онлайн",
    rating_filter: "Мин. рейтинг",
    score: "Счёт",
    tokens: "Токены",
    turn: "Ход",
    leave: "Выйти"
  },
  es: {
    age_title: "Confirmación de edad",
    age_text: "Debes tener 18+ para jugar. Confirma para continuar.",
    age_btn: "Tengo 18+",
    login_title: "Iniciar sesión",
    email: "Correo",
    password: "Contraseña",
    login_btn: "Entrar",
    forgot: "¿Olvidaste la contraseña?",
    no_account: "¿Sin cuenta?",
    to_register: "Crear cuenta",
    register_title: "Registro",
    rating: "Rating inicial",
    avatar: "Avatar",
    register_btn: "Registrar",
    to_login: "Volver",
    lobby_title: "Lobby",
    difficulty: "Dificultad",
    mode: "Modo",
    duel: "Duelo (2 jugadores)",
    solo: "Solo",
    create_table: "Crear mesa",
    active_tables: "Mesas activas",
    online_players: "Jugadores en línea",
    rating_filter: "Rating mínimo",
    score: "Puntos",
    tokens: "Tokens",
    turn: "Turno",
    leave: "Salir"
  }
};

export function applyLang(lang='en'){
  const t = dict[lang] || dict.en;
  document.querySelectorAll("[data-i18n]").forEach(el=>{
    const key = el.getAttribute("data-i18n");
    if(t[key]) el.textContent = t[key];
  });
  document.documentElement.lang = lang;
}
